## 101 Excercises for Numpy

### Difficulty Level: L1

1.  Import numpy as np and see the version

In [8]:
import numpy as np
np.__version__


'1.16.5'

2.  Create a 1D array of numbers from 0 to 9

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3.  Create a 3×3 numpy array of all True’s

In [26]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4.  Extract all odd numbers from ``arr``

``arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])``

In [52]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

5.  Replace all odd numbers in ``arr`` with -1

In [44]:
#Native Method
for i in arr:
    if arr[i]%2!=0:
        arr[i]=-1
        
print("Changed Array by Method 1 is:-",arr)

In [39]:
#Neat way
arr[arr%2!=0]=-1
print("Changed Array by Method 2 is:-",arr)

6.  How to replace items that satisfy a condition without affecting the original array?
 * Replace all odd numbers in ``arr`` with -1 without changing ``arr``

In [54]:
print(np.where(arr%2!=0,-1,arr))
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


7.  Convert a 1D array to a 2D array with 2 rows

``np.arange(10)``

``#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])``

In [56]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8.  Stack arrays ``a`` and ``b`` vertically

``a = np.arange(10).reshape(2,-1)``

``b = np.repeat(1, 10).reshape(2,-1)``

9. How to stack two arrays horizontally?