In [ ]:
import numpy as np

In [151]:
arr_3D=np.arange(8).reshape(2,2,2)

In [161]:
np.sum(arr_3D,axis=0)

array([[ 4,  6],
       [ 8, 10]])

In [162]:
arr_3D[0][0][0]+arr_3D[0][0][1]

0

In [154]:
arr_4D=np.arange(16).reshape(2,2,2,2)

In [156]:
arr_4D

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [157]:
np.sum(arr_4D,axis=0)

array([[[ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22]]])